HMS/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserAuthentication.urls')),
    path('Patient/', include('patient.urls')),
    path('Doctor/', include('doctor.urls')),
    path('Manager/', include('manager.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserAuthentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home , name="home"),
    path("login" , views.login_user , name="login"),
    path("register" , views.register , name="register"),
    path("logout" , views.sinout , name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='rest_password.html'), name = "reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_confirm.html'),name = "password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='rest_complete.html'), name="password_reset_complete"),
]

doctor/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from patient.models import *


class Specialization(models.Model):

    name = models.CharField(max_length=100,  blank=True, null=True,unique=True)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    GenderChoices = (
        ('male', 'male'),
        ('female', 'female'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)
    Specialization = models.ForeignKey(
        Specialization, on_delete=models.CASCADE, null=True)
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    profile_img = models.ImageField(
        upload_to='profile_images', default='default-profile-image-png-1-Transparent-Images.png')
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(
        max_length=100, blank=True, null=True, default="None")
    salary = models.IntegerField(default=250)
    address = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(
        max_length=6, choices=GenderChoices, blank=True, null=True, default="male")

    def __str__(self):
        return self.user.username


class docter_schedule(models.Model):

    Date_Book = models.DateField(blank=True, null=True)
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, blank=True, null=True)
    data1 = models.BooleanField(default=False)
    data2 = models.BooleanField(default=False)
    data3 = models.BooleanField(default=False)
    data4 = models.BooleanField(default=False)
    data5 = models.BooleanField(default=False)
    data6 = models.BooleanField(default=False)

    def __str__(self):
        if self.data1 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("08 to 10 AM")
        elif self.data2 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("10 to 12 PM")
        elif self.data3 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("12 to 01 PM")
        elif self.data4 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("01 to 02 PM")
        elif self.data5 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("02 to 04 PM")
        elif self.data6 == False:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' form ' + str("04 to 06 PM")
        else:
            x = 'Dr.' + str(self.doctor.user) + ' at day ' + str(self.Date_Book) + ' is ' + str("Full")
        return x

    # def save(self, *args, **kwargs):
    #     super(Doctor, self).save(*args, **kwargs)
    # def create_Doctor(sender, **kwargs):
    #     if kwargs['created']:
    #         print(type(kwargs['instance']))
    #         Doctor.objects.create(user=kwargs['instance'])
    #
    # post_save.connect(create_Doctor, sender=User)
class Appointment(models.Model):
    name = models.CharField(max_length=100)
    patient = models.ForeignKey( Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey( Doctor, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    data_time = models.CharField(max_length=100)
    descrption = models.TextField(max_length=500, blank=True, null=True,default="None")
    def __str__(self):
        return str(self.patient)+" have appointment with Dr."+str(self.doctor)

UserAuthentication/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CreateNewUser(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(CreateNewUser, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {
            'placeholder': 'Enter your username', 'autofocus': False}
        self.fields['first_name'].widget.attrs = {
            'placeholder': 'Enter your name', 'required': True}
        self.fields['email'].widget.attrs = {
            'placeholder': 'Enter your email', 'required': True}
        self.fields['password1'].widget.attrs = {
            'placeholder': 'Enter your password' ,'id':'password1'}
        self.fields['password2'].widget.attrs = {
            'placeholder': 'Enter your again password','id':'password2'}

    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'password1', 'password2']

UserAuthentication/views.py
from django.shortcuts import render, redirect
from .forms import CreateNewUser
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib import messages
from patient.models import Patient
from django.contrib.auth.models import User
from django.db.models import *
from .models import *
from doctor.models import Doctor
from manager.models import Manager

# Create your views here.
def home(request):
    all_doctor=Doctor.objects.all()
    return render(request,'index.html',{'all_doctor':all_doctor})

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username , password =password)
        if user is not None:
            patient_user = Patient.objects.filter(user=user).first()
            doctor_user = Doctor.objects.filter(user=user).first()
            manager_user = Manager.objects.filter(user=user).first()
            if patient_user is not None:
               # messages.info(request,patient_user)
               login(request, user)
               return redirect('/Patient/Dashboard')
            elif doctor_user is not None:
                # messages.info(request, doctor_user)
                login(request, user)
                return redirect('/Doctor/Dashboard')
            else:
                # messages.info(request, manager_user)
                login(request, user)
                return redirect('/Manager/Dashboard')
                
        else:
            messages.info(request , "Invaild username or password")
    return render(request , 'login.html')

def register(request):
    
    if request.method == 'POST':
        form = CreateNewUser(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            form.save()
            Patient.objects.create(user=user).save()
            return redirect('login')
    else:
          form = CreateNewUser()


    return render(request , 'signup.html' , {'form': form})
def sinout(request):
    logout(request)
    return redirect('home')

UserAuthentication/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>project</title>
  <!-- <link rel="icon" href="2022-11-12 02_16_41-navbar.png"> -->
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/index.style.css'%}">
  <link rel="stylesheet" href="{% static 'home/css/all.min.css'%}">
  <link rel="preconnect" href="https://fonts.googleapis.com' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">

</head>

<body>

  <!-- start navbar-->
  <div class="header">
    <div class="con" style="position: relative;">
      <div class="loh">
        <i class="fa-solid fa-stethoscope"><span class="clog"><span>m</span>edical <span>c</span>are</span></i>
      </div>
      <div class="links">
        <span class="icon">
          <span></span>
          <span></span>
          <span></span>
        </span>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#About">About</a></li>
          <li><a href="#Contact">Contact</a></li>
<!--          <li>-->
<!--            <div class="photo"> <a href=""><img class="logo"-->
<!--                  src="{% static 'home/navbar/images/240_F_137440378_5mMBNu4Xyxaj25zD8Ag8NQWsOkYKDeq8.jpg'%}" alt="Erorr"></a></div>-->
<!--          </li>-->
          <li><a href="login" ><button class="btn-log">login</button></a></li>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <!-- end navbar-->

  <!-- start slide show -->
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <!-- <div class="landing"></div> -->
    <div class="caption">
      <h2>The Best Medical Services</h2>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non maiores inventore fugiat omnis, dicta ipsum
        repellendus quam modi dolore hic id expedita nam accusantium incidunt nulla aliquam aliquid laboriosam amet.</p>
      <button class="rbtn">read more</button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'home/navbar/images/9.jpeg'%}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'home/navbar/images/1.jpg'%}" class="d-block w-100"
          alt="...">
      </div>

      <div class="carousel-item">
        <img src="{% static 'home/navbar/images/2.webp' %}"
          class="d-block w-100" alt="...">
      </div>
    </div>




    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>



    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

    
  </div>
  <!-- end slide show -->
  
  
  <!-- start portfolio-->
  <div class="portfolio" id="portfolio">
    <div class="component">
      <h2>portfolio</h2>
      <div></div>
      <div class="circle"></div>
      <div></div>
      <p>Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Mauris blandit aliquet elit, eget
        tincidunt</p>
    </div>
    <div class="cards">
      {% for doctor in all_doctor %}
      <div class="card">
        <img src="{{doctor.profile_img.url}}" alt="Avatar" style="width:100%">
        <div class="card-data">
          <h4><b>Dr.{{doctor.name}}</b></h4>
          <p>{{doctor.Specialization}}</p>
        </div>
        <div class="ico">
          <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
          <a href="#"><i class="fa-brands fa-twitter"></i></a>
          <a href="#"><i class="fa-brands fa-google"></i></a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- start about us -->
  <div class="aboutus">
    <div class="about-section">
      <h1>About Our Hospital</h1>
      <p>There are many variations of passages of Lorem have suffered alteration in sthiator on the Internet. It uses a
        dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem
        Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected
        humour, or non-characteristic words etc. able. The generated Lorem Ipsum is therefore always free from
        repetition, injected humou</p>
    </div>

    <h2 class="card-caption">Our Team</h2>
    <div class="content">
      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG_20221025_211204.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>karim abdelazim</p>
          <p>front end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG20221127105618.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>basem yahia</p>
          <p>front end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG-20221110-WA0093.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>ahmed ebrahim</p>
          <p>front end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG_20211130_032204.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>eslam nady</p>
          <p>front end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG-20221110-WA0094.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>khaled mohamed</p>
          <p>back end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/IMG-20221207-WA0034.jpg'%}" alt="">
        </div>
        <div class="project-info">
          <p>ahmed gubran</p>
          <p>back end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>


      <div class="project-card">
        <div class="project-image">
          <img src="{% static 'home/images/WhatsApp Image 2022-08-23 at 9.11.37 PM.jpeg'%}" alt="">
        </div>
        <div class="project-info">
          <p>Sherif Ahmed</p>
          <p>back end</p>
          <div class="contcat-me">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-github"></i></a>
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- end about us -->




  <!-- start contact us -->
  <div class="component" id="Contact">
    <h2>contact us</h2>
    <div></div>
    <div class="circle"></div>
    <div></div>
    <p>Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Mauris blandit aliquet elit, eget
      tincidunt</p>
  </div>
  


  <div class="parent" id="">
    <div class="contain">

      <div class="caption-text">Contact with us</div>
      <form action="#" class="cform">
        <div class="form-row">
          <div class="input-data">
            <input type="caption-text" required>
            <div class="underline"></div>
            <label for="">First Name</label>
          </div>
          <div class="input-data">
            <input type="caption-text" required>
            <div class="underline"></div>
            <label for="">Last Name</label>
          </div>
        </div>
        <div class="form-row">
          <div class="input-data">
            <input type="caption-text" required>
            <div class="underline"></div>
            <label for="">Email Address</label>
          </div>
          <div class="input-data">
            <input type="caption-text" required>
            <div class="underline"></div>
            <label for="">Phone</label>
          </div>
        </div>
        <div class="form-row">
          <div class="input-data textarea">
            <textarea rows="8" cols="80" required></textarea>
            <br />
            <div class="underline"></div>
            <label for="">Write your message</label>
            <br />
          </div>
        </div>
        <div class="btn">
          <input type="submit" value="submit">
        </div>
      </form>
    </div>
  </div>




  <!-- end contact us -->

  
  <!-- start footer-->

  <footer>
    <div class="content-footer">
      <div class="top">
        <div class="logo-details">
          <i class="fa fa-heartbeat" style="font-size:30px;"></i>
          <span class="logo_name">medical care</span>
        </div>
        <div class="media-icons">
          <a href="#"><i class="fab fa-facebook-f"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
          <a href="#"><i class="fab fa-youtube"></i></a>
        </div>
      </div>
      <div class="link-boxes">
        <ul class="box">
          <li class="link_name">Company</li>
          <li><a href="#">Home</a></li>
          <li><a href="#">Department</a></li>
          <li><a href="#">Find a Docter</a></li>
          <li><a href="#">News</a></li>
        </ul>
        <ul class="box">
          <li class="link_name">Quick Links</li>
          <li><a href="#">Facial Fillers</a></li>
          <li><a href="#">Breast Surgery</a></li>
          <li><a href="#">Body Lifts</a></li>
          <li><a href="#">Face & Neck</a></li>
          <li><a href="#">Fat Reduction</a></li>
        </ul>
        <ul class="box">
          <li class="link_name">Contact Us</li>
          <li><i class="fa fa-map-marker"></i> Los Angeles Gournadi, 1230 Bariasl</li>
          <li><i class="fa fa-phone"></i> 1-677-124-44227</li>
          <li><i class="fa fa-envelope"></i> <a href="/cdn-cgi/l/email-protection" class="__cf_email__"
              data-cfemail="a0f3d5d0d0cfd2d4e0c7cdc1c9cc8ec3cfcd">basem@gmail.com</a></li>
        </ul>
        <ul class="box input-box">
          <li class="link_name">Subscribe</li>
          <form action="">
            <li><input type="text" placeholder="Enter your email"></li>
            <li><input type="button" value="Subscribe"></li>
          </form>
        </ul>
      </div>
    </div>
    <div class="bottom-details">
      <div class="bottom_text">
        <span class="copyright_text">Copyright © 2022<a href="#"> Save life</a>All rights reserved</span>
        <span class="policy_terms">
          <a href="#">Privacy policy</a>
          <a href="#">Terms & condition</a>
        </span>
      </div>
    </div>
  </footer>
  <!-- end footer-->

  <script src="{% static 'home/js/popper.min.js'%}"></script>
  <script src="{% static 'home/js/jquery-3.5.0.min.js'%}"></script>
  <script src="{% static 'home/js/bootstrap.min.js'%}"></script>

  <script src="{% static 'home/js/index.js'%}"></script>
</body>

</html>

UserAuthentication/templates/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>log in</title>
    <!-- main template css file -->
    <link rel="stylesheet" href="{% static 'Css/style.css' %}" />
    <!-- font awesome library -->
    <link
      rel="stylesheet"
      href="{% static 'fontawesomefree/Css/all.min.css' %}"
    />
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <!--start login-->
    <div class="log" id="id01">
      <div class="lgn">
        <div class="logsi">
          <h1><a href="login">Login</a></h1>
          <h1><a href="register">Sign Up</a></h1>
        </div>
        <div class="error_login">
          {% for message in messages %}
          <li {% if message.errors %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
          </li>
          {% endfor %}
        </div>

        <form method="POST">
          {% csrf_token %}
          <div class="input">
            <i class="fa-solid fa-user"></i>
            <input
              type="text"
              name="username"
              id=""
              placeholder="type your username"
              required
            />
          </div>
          <div class="input">
            <i class="fa-solid fa-lock"></i>
            <input
              type="password"
              name="password"
              id="password"
              placeholder="type your password"
              required
            />
                <span class="eye">
                    <i id="hide2" class="fa-regular fa-eye-slash"></i>
                    <i id="hide1" class="fa-regular fa-eye"></i>
                </span>
          </div>
          <div class="lin">
            <a href="reset_password">Forgot password?</a>
          </div>
          <div class="btn">
            <input type="submit" value="login" />
          </div>
        </form>
        <p>Or Sign Up Using</p>
        <div class="icon">
          <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
          <a href="#"><i class="fa-brands fa-twitter"></i></a>
          <a href="#"><i class="fa-brands fa-google"></i></a>
        </div>
      </div>
    </div>
    <!--end login-->

    <script src="{% static '/Js/index.js' %}"></script>


    <script src="{% static '/js/index.js' %}"></script>
    <!-- <script src="{% static '/js/all.min.js' %}"></script> -->


  </body>
</html>

UserAuthentication/templates/password_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forget password</title>
    <!-- main template css file -->
    <link rel="stylesheet" href="{% static 'forgetpassword/repeat_password.css'%}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{% static 'all.min.css'%}">
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="row">
            <h1>Forget Password</h1>
            <h6 class="information-text">Please enter (and confirm) your new password</h6>

    {% if validlink %}

        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}

            <div class="footer">
                <h5>Already have an account? <a href="/login">Log In.</a></h5>
            </div>
        </div>
    </div>
</body>

</html>

UserAuthentication/templates/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- main template css file -->
    <link rel="stylesheet" href="{% static 'forgetpassword/style_mss.css'%}">
     <!-- font awesome library -->
     <link rel="stylesheet" href="{% static 'forgetpassword/all.min.css'%}">
     <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">
</head>

<body>


		<div class="container" >
<div class="mss">
	<div class="d-flex flex-column">
		  <p class="m-auto p-2" >
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home' %}">Return to home page</a></p>
	</div>
	</div>
</div>




</body>

</html>

UserAuthentication/templates/rest_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- main template css file -->
    <link rel="stylesheet" href="{% static 'forgetpassword/style_mss.css'%}">
     <!-- font awesome library -->
     <link rel="stylesheet" href="{% static 'forgetpassword/all.min.css'%}">
     <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="mss">


	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
	</div>
          </div>
</div>
</body>

</html>

UserAuthentication/templates/rest_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forget password</title>
    <!-- main template css file -->
    <link rel="stylesheet" href="{% static 'forgetpassword/style.css'%}">
     <!-- font awesome library -->
     <link rel="stylesheet" href="{% static 'forgetpassword/all.min.css'%}">
     <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="row">
            <h1>Forgot Password</h1>
            <h6 class="information-text">Enter your registered email to reset your password.</h6>
<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
  <i class="fa-solid fa-envelope"></i>

    <input name="email" class="form-control" placeholder="Type your email" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>
</form>
            <div class="footer">
                <h5>New here? <a href="{% url 'register' %}">Sign Up.</a></h5>
                <h5>Already have an account? <a href="{% url 'login' %}">Log In.</a></h5>
            </div>
        </div>
    </div>
</body>

</html>